version: '3'
services:
  playground:
    image: nginx:latest
    volumes:
      - ./public:/usr/share/nginx/html:ro
    ports:
      - "9600:80"
    networks:
      - mad_network

networks:
  mad_network:
    driver: bridge
